### ISSUE TITLE
Some early versions of Python 3.5 don't work with aiocontextvars

### ISSUE THREAD

**Issue by itamarst** [fantix/aiocontextvars#88]
* aiocontextvars version: 0.2.2
* Python version: 3.5.2
* Ubuntu Xenial LTS

Original bug report: https://github.com/matrix-org/synapse/issues/5199

### Description

On Ubuntu Xenial supported Python 3.5 is 3.5.2.

On Python 3.5.2 `asyncio` doesn't have `asyncio._get_running_loop`.

Example traceback (copied from https://github.com/itamarst/eliot/issues/418#issue-446120974):

```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eliot
>>> eliot.current_action()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/synapse/env3/lib/python3.5/site-packages/eliot/_action.py", line 53, in current_action
    return _ACTION_CONTEXT.get(None)
  File "/home/synapse/env3/lib/python3.5/site-packages/contextvars/__init__.py", line 94, in get
    ctx = _get_context()
  File "/home/synapse/env3/lib/python3.5/site-packages/aiocontextvars.py", line 19, in _get_context
    state = _get_state()
  File "/home/synapse/env3/lib/python3.5/site-packages/aiocontextvars.py", line 33, in _get_state
    loop = asyncio._get_running_loop()
AttributeError: module 'asyncio' has no attribute '_get_running_loop'
```

### Solution

Haven't tried this yet, but:

```python
if sys.version_info < (3, 5, 3):
    import asyncio
    from asyncio import events
    asyncio._get_running_loop = events._get_running_loop
    asyncio._set_running_loop = events._set_running_loop
```

**Comment by itamarst** [comment]
Actually I'm not what point release has the fix, so maybe:

```python
    import asyncio
    if getattr(asyncio, "_get_running_loop", None) is None:
        from asyncio import events
        asyncio._get_running_loop = events._get_running_loop
        asyncio._set_running_loop = events._set_running_loop
        del events
```

**Comment by itamarst** [comment]
Actually, the above won't work. Might need a whole bunch of copy from latest 3.5 `events.py` :(

**Comment by itamarst** [comment]
Looks like:

1. 3.5.3 doesn't have the problem.
2. The specific commit to 3.5.3 that added `_get_running_loop` is https://github.com/python/cpython/commit/600a349781bfa0a8239e1cb95fac29c7c4a3302e#diff-26d371a128a335a2c69b3f38613631fd

**Comment by nickwilliams-eventbrite** [comment]
I was optimistic about using this, but we're stuck on Python 3.5.2 because Ubuntu 16.04 is stuck on Python 3.5.2. :-(

**Comment by nickwilliams-eventbrite** [comment]
For what it is worth, I was able to use `aiocontextvars` with some patching of my own. Not great, but now everything works in Python 3.5 and 3.6:

```python
if (3, 4) < sys.version_info < (3, 7):
    import asyncio
    import asyncio.coroutines
    import asyncio.futures
    import concurrent.futures

    if not hasattr(asyncio, '_get_running_loop'):
        # noinspection PyCompatibility
        import asyncio.events
        from threading import local as threading_local

        if not hasattr(asyncio.events, '_get_running_loop'):
            class _RunningLoop(threading_local):
                _loop = None

            _running_loop = _RunningLoop()

            def _get_running_loop():
                return _running_loop._loop

            def set_running_loop(loop):  # noqa: F811
                _running_loop._loop = loop

            def _get_event_loop():
                current_loop = _get_running_loop()
                if current_loop is not None:
                    return current_loop
                return asyncio.events.get_event_loop_policy().get_event_loop()

            asyncio.events.get_event_loop = _get_event_loop
            asyncio.events._get_running_loop = _get_running_loop
            asyncio.events._set_running_loop = set_running_loop

        asyncio._get_running_loop = asyncio.events._get_running_loop
        asyncio._set_running_loop = asyncio.events._set_running_loop

    # It needs only to be imported to activate the patching of the contextvars backport (see the comment in setup.py)
    # noinspection PyUnresolvedReferences
    import aiocontextvars  # noqa

    def _run_coroutine_threadsafe(coro, loop):
        """
        Patch to create task in the same thread instead of in the callback. This ensures that contextvars get copied.
        Python 3.7 copies contextvars without this.
        """
        if not asyncio.coroutines.iscoroutine(coro):
            raise TypeError('A coroutine object is required')
        future = concurrent.futures.Future()
        task = asyncio.ensure_future(coro, loop=loop)

        def callback():
            try:
                # noinspection PyProtectedMember,PyUnresolvedReferences
                asyncio.futures._chain_future(task, future)
            except Exception as exc:
                if future.set_running_or_notify_cancel():
                    future.set_exception(exc)
                raise

        loop.call_soon_threadsafe(callback)
        return future

    asyncio.run_coroutine_threadsafe = _run_coroutine_threadsafe
```
